### ISSUE TITLE
make exits with error 

### ISSUE THREAD

**Issue by changliwei** [bearstech/e2find#2]
`apt-get install make gcc e2fslibs-dev comerr-dev libblkid-dev

root@VM-106-180-ubuntu:~/e2find# make

gcc -O2 -Wall -lext2fs -lcom_err -lblkid -o e2find e2find.c

/tmp/ccgPW0xj.o: In function `main':

e2find.c:(.text.startup+0x1c8): undefined reference to `blkid_devno_to_devname'

e2find.c:(.text.startup+0x20b): undefined reference to `unix_io_manager'

e2find.c:(.text.startup+0x223): undefined reference to `ext2fs_open'

e2find.c:(.text.startup+0x333): undefined reference to `ext2fs_open_inode_scan'

e2find.c:(.text.startup+0x370): undefined reference to `ext2fs_get_next_inode'

e2find.c:(.text.startup+0x4bb): undefined reference to `ext2fs_close_inode_scan'

e2find.c:(.text.startup+0x50f): undefined reference to `ext2fs_dir_iterate'

e2find.c:(.text.startup+0x5dd): undefined reference to `ext2fs_close'

collect2: error: ld returned 1 exit status

Makefile:10: recipe for target 'e2find' failed

make: *** [e2find] Error 1

root@VM-106-180-ubuntu:~/e2find# cat /etc/issue

Ubuntu 16.04.1 LTS \n \l
`
can not make

**Comment by zerodeux** [comment]
I could reproduce your problem, I'm having a look.
